<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1517994842008' stop='1517994887524'>
    <name>PullTest</name>
    <title>PullTest</title>
    <test-cases>
        <test-case start='1517994842009' status='passed' stop='1517994850860'>
            <name>Validate user name</name>
            <title>Validate user name</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1517994850860' status='passed' stop='1517994858994'>
            <name>Check exit for yandex</name>
            <title>Check exit for yandex</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1517994858994' status='passed' stop='1517994862011'>
            <name>Incorrect password</name>
            <title>Incorrect password</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1517994862011' status='passed' stop='1517994864739'>
            <name>Incorrect login</name>
            <title>Incorrect login</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1517994864739' status='passed' stop='1517994882353'>
            <name>Test navigation</name>
            <title>Test navigation</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1517994882353' status='failed' stop='1517994887524'>
            <name>Test english version</name>
            <title>Test english version</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Expected false to be true.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (C:\Work\Protractor\PullTest\pull-spec.js:62:37)
                    at C:\Users\Fokiruna\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
                    at new ManagedPromise (C:\Users\Fokiruna\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at ControlFlow.promise (C:\Users\Fokiruna\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
                    at schedulerExecute (C:\Users\Fokiruna\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
                    at TaskQueue.execute_ (C:\Users\Fokiruna\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\Fokiruna\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\Fokiruna\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25)
                    at C:\Users\Fokiruna\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>